language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install flake8 . --use-mirrors 
before_script:
  - "flake8 --show-source --builtins=_ PyTd"
script:
  - echo "Need to figure what tests can run outside corproate network..."
